text = 'CAATAATCACAATAATCACGTTAAGGCAATAATCACAGTTCGCGTTAAGGCGTTAAGGATAGATTATAGATTCGTTAAGGATAGATTATAGATTCAGTTCGTAACCGAAATAGATTCAGTTCGCAATAATCAATAGATTTAACCGAACGTTAAGGCAATAATCACAATAATCATAACCGAATAACCGAACGTTAAGGTAACCGAACAATAATCACGTTAAGGATAGATTCGTTAAGGATAGATTTAACCGAAATAGATTCAGTTCGCAATAATCACGTTAAGGTAACCGAATAACCGAACAATAATCAATAGATTCAATAATCAATAGATTTAACCGAATAACCGAACAATAATCACGTTAAGGCGTTAAGGTAACCGAACGTTAAGGATAGATTCGTTAAGGATAGATTCGTTAAGGATAGATTCAATAATCACAGTTCGTAACCGAACAATAATCATAACCGAATAACCGAAATAGATTCAGTTCGCAATAATCACGTTAAGGCGTTAAGGTAACCGAAATAGATTTAACCGAACAGTTCGATAGATTCGTTAAGGATAGATTTAACCGAACGTTAAGGCAGTTCGCGTTAAGGATAGATTCAATAATCACAATAATCAATAGATTATAGATTCAATAATCAATAGATTTAACCGAATAACCGAACAGTTCGCAATAATCACAGTTCGTAACCGAACGTTAAGGTAACCGAACAGTTCGCAGTTCGCAGTTCGCAATAATCACGTTAAGGCAATAATCACGTTAAGGCAATAATCACAGTTCGATAGATTCAATAATCATAACCGAATAACCGAACAATAATCA'
k = 14

fregs = {}

for i in xrange (0, len(text)- k+1):
    if text[i:i+ k] in fregs:
        fregs[text[i:i+ k]] = fregs[text[i:i+ k]] + 1
    else:
        fregs[text[i:i+ k]] = 1
for key, value in fregs.items():
    if value == max(fregs.values()):
        print key,